services:
  backend:
    container_name: backend
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - esg_network

  frontend:
    container_name: frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - esg_network

  db:
    container_name: mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    working_dir: /var/lib/mysql
    command: --bind-address=0.0.0.0
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3307:3306
    volumes:
      - ESG_db:/var/lib/mysql
      #- ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "ESG_db"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #environment:
    # MYSQL_DATABASE: 'ESG_db'
    # So you don't have to use root, but you can if you like
    #MYSQL_USER: 'user'
    # You can use whatever password you like
    #MYSQL_PASSWORD: 'carbon2024'
    # Password for root access
    #MYSQL_ROOT_PASSWORD: 'carbon2024'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} && mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'show databases;'",
        ]
      timeout: 25s
      retries: 10
    networks:
      - esg_network

volumes:
  ESG_db:

networks:
  esg_network:
