export const SET_ESG_PAGE = 'esg/SET_ESG_PAGE';
export const SET_BOUNDARY_EDITION_PAGE = 'esg/SET_BOUNDARY_EDITION_PAGE';
export const SET_SOURCE_PAGE = 'esg/SET_SOURCE_PAGE';
export const SET_STATEMENT_PAGE = 'esg/SET_STATEMENT_PAGE';
export const SET_AUDIT_PAGE = 'esg/SET_AUDIT_PAGE';

export const RETRIEVE_BOUNDARY = 'esg/RETRIEVE_BOUNDARY';
export const RETRIEVE_SOURCE = 'esg/RETRIEVE_SOURCE';
export const RETRIEVE_STATEMENT = 'esg/RETRIEVE_STATEMENT';

export const PN_LIST = 'esg/PN_LIST';